name       : cantata
version    : 2.3.1
release    : 9
source     :
    - https://github.com/CDrummond/cantata/releases/download/v2.3.1/cantata-2.3.1.tar.bz2 : 5b1e563ec125d57296495d0f8f97eeecf0b2260aa50b35bae7cab221d7914eb4
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : Cantata is a graphical client for MPD
description: |
    Cantata is a (yet another!) client for the music player daemon (MPD). Originally started as a fork of QtMPC, the code is now *very* different. The interface is very configurable - most views can be shown as either a list or tree structure.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(avahi-client)
    - pkgconfig(gl)
    - pkgconfig(libavcodec)
    - pkgconfig(libcddb)
    - pkgconfig(libcdio_paranoia)
    - pkgconfig(libmpg123)
    - pkgconfig(libmtp)
    - pkgconfig(libmusicbrainz5)
    - pkgconfig(libvlc)
    - pkgconfig(taglib)
    - media-player-info
rundeps    :
    - mpd
    - perl-uri
setup      : |
    %cmake_ninja -DENABLE_REMOTE_DEVICES=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
