name       : cantata
version    : 2.3.0
release    : 7
source     :
    - https://github.com/CDrummond/cantata/releases/download/v2.3.0/cantata-2.3.0.tar.bz2 : 15a4496cdacbb6d22880dcca3011bd0d7738fc07b03e34aa745d1533c7f33db7
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : Cantata is a graphical client for MPD
description: |
    Cantata is a (yet another!) client for the music player daemon (MPD). Originally started as a fork of QtMPC, the code is now *very* different. The interface is very configurable - most views can be shown as either a list or tree structure.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(avahi-client)
    - pkgconfig(gl)
    - pkgconfig(libavcodec)
    - pkgconfig(libcddb)
    - pkgconfig(libcdio_paranoia)
    - pkgconfig(libmpg123)
    - pkgconfig(libmtp)
    - pkgconfig(libmusicbrainz5)
    - pkgconfig(libvlc)
    - pkgconfig(taglib)
    - media-player-info
rundeps    :
    - mpd
    - perl-uri
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-some-paths.patch

    %cmake . -DCANTATA_HELPERS_LIB_DIR=%libdir%
build      : |
    %make
install    : |
    %make_install
